awwards/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views 
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('projects.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}), 
    url(r'^api-token-auth/', obtain_auth_token)
]

projects/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns=[
    url('^$',views.index,name = 'home'),
    url(r'^signup', views.signup, name='signup'),
    url(r'^login', LoginView.as_view(), name='login_url'),
    url(r'^logout/', LogoutView.as_view(next_page='login_url'), name='logout_url'),
    url(r'^new/project', views.new_project, name='new_project'),
    url(r'^user/profile', views.profile, name='profile'),
    url(r'^project/(?P<id>\d+)$', views.project, name='project'),
    url(r'^user/<int:user_id>', views.posted_by, name='posted_by'),
    url(r'^update/user/',views.update_profile, name='update_profile'),
    url(r'^project/(?P<id>\d+)/vote/$',views.vote, name='vote'),
    url(r'^api/$', views.api, name='api'),
    url(r'^api/project/$', views.ProjectList.as_view()),
    url(r'^api/users/$', views.UserList.as_view()),
    url(r'^api/project/<int:pk>/$',views.ProjectDescription.as_view()),
    url(r'^api/user/<int:pk>/$',views.UserDescription.as_view()),
    url(r'^search/', views.search_project, name='search'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator

# Models.
class Project(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='project/', default='No image')
    title=models.CharField(max_length=60)
    description=models.TextField()
    link=models.CharField(max_length=100)
    location=models.CharField(max_length=30)
    posted=models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.title
    
    def save_project(self):
        self.save()
    
    @classmethod    
    def get_project(cls, id):
        project=Project.objects.get(pk=id)
        return project

    @classmethod
    def search_project(cls, search_term):
        user = cls.objects.filter(title__icontains=search_term)
        return project 
    
    @classmethod   
    def delete_project(cls,delete_id):
        Project.objects.filter(pk=delete_id).delete()
        
        
class Votes(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    usability=models.IntegerField(default=0, validators=[MaxValueValidator(10,message='Range acceptable is 0-10'), MinValueValidator(0)])
    design=models.IntegerField(default=0, validators=[MaxValueValidator(10,message='Range acceptable is 0-10'), MinValueValidator(0)])
    content=models.IntegerField(default=0, validators=[MaxValueValidator(10,message='Range acceptable is 0-10'), MinValueValidator(0)])
    
    def __str__(self):
        return self.user.username
    
    def save_vote(self):
        self.save()
    
class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='profile/', default='default.png')
    bio=models.TextField(blank=True)
    contact=models.CharField(max_length=30, blank=True)
    location=models.CharField(max_length=50,  blank=True)
    company=models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        return self.user.username
    
    def save_profile(self):
        self.save()

projects/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile,Project,Votes
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    email = forms.EmailField(max_length=254, required=True)

    class Meta:
        model = User
        fields = ('email' ,'username','password1', 'password2', )

class UpdateUser(forms.ModelForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username', 'email']
        
class UpdateProfile(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['contact','location','company','bio','image',]
        
        
        
class PostProject(forms.ModelForm):
    class Meta:
        model=Project
        fields=['image','title','description','link','location']
        
class Voting(forms.ModelForm):
    class Meta:
        model=Votes
        fields=['usability','design','content']

projects/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http  import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Profile,Project,Votes
from .forms import PostProject,UpdateUser,UpdateProfile,SignUpForm,Voting
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import ProjectSerailizer,UserSerializer
from rest_framework import status
from .permission import IsAdminOrReadOnly
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
import numpy as np

# Views
# Index view
@login_required
def index(request):
    # Default view
    projects = Project.objects.order_by('-posted')
    profiles = Profile.objects.all()
    return render(request,'project/index.html', {'projects':projects, 'profiles':profiles})

# User profile view
@login_required
def profile(request):
    return render(request,'project/profile.html')

#specific project
@login_required
def project(request, id):
    form = Voting
    project= Project.objects.get(id=id)
    votes= Voting()
    votes_list=project.votes_set.all()
    for vote in votes_list:
            vote_mean=[]
            usability=vote.usability
            vote_mean.append(usability)
            content=vote.content
            vote_mean.append(content)
            design=vote.design
            vote_mean.append(design)
            mean=np.mean(vote_mean)
            mean=round(mean,2)
            if mean:
                return render(request, 'project/project.html',{'project':project,'votes':votes,'votes_list':votes_list,'mean':mean,'form':form})

    return render(request, 'project/project.html',{'project':project,'votes':votes,'votes_list':votes_list, 'form':form})

@login_required
def vote(request, id):
    project= Project.objects.get(id=id)
    votes=Voting()
    votes=Voting(request.POST)
    if votes.is_valid():
        vote=votes.save(commit=False)
        vote.user=request.user
        vote.project=project
        vote.save() 
        messages.success(request,'Votes Successfully submitted')
        return HttpResponseRedirect(reverse('project',  args=(id)))
    
    else:
        messages.warning(request,'ERROR! Voting Range is from 0-10')
        votes=Voting()     
    return render(request, 'project/project.html', locals())

@login_required
def new_project(request):
    current_user=request.user
    if request.method=='POST':
        form=PostProject(request.POST,request.FILES)
        if form.is_valid():
            project=form.save(commit=False)
            project.user=current_user
            project.save()
        return redirect('home')
    
    else:
        form=PostProject()
        
    return render(request,'project/new_project.html',{'form':form})

@login_required
def posted_by(request, user_id):
    user=get_object_or_404(User,pk=user_id)
    return render(request,'project/posted_by.html', {'user':user})

def signup(request):
    name = "Sign Up"
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            name = form.cleaned_data.get('username')
            send_mail(
            'Welcome to Awwards Gallery App.',
            f'Hello {name},\n '
            'Welcome to Instagram App and have fun.',
            'nyururukelvin99@gmail.com@gmail.com',
            [email],
            fail_silently=False,
            )
        return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/registration_form.html', {'form': form, 'name':name})

def search_project(request):
    """
    Function that searches for projects
    """
    if 'project' in request.GET and request.GET["project"]:
        search_term = request.GET.get("project")
        searched_projects = Project.objects.filter(title__icontains=search_term)
        message = f"{search_term}"
        projects = Project.objects.all()
        
        return render(request, 'project/search.html', {"message": message, "projects": searched_projects})

    else:
        message = "You haven't searched for any term"
        return render(request, 'search.html', {"message": message})

def update_profile(request):
    profile = Profile(user=request.user)

    update_user=UpdateUser(request.POST,instance=request.user)
    update_profile=UpdateProfile(request.POST,request.FILES,instance=profile)
    if update_user.is_valid() and update_profile.is_valid():
        update_user.save()
        update_profile.save()
        
        messages.success(request, 'Profile Updated Successfully')
        return redirect('profile')
    
    else:
        update_user=UpdateUser(instance=request.user)
        update_profile=UpdateProfile(instance=profile)
    return render(request, 'project/update_profile.html',{'update_user':update_user,'update_profile':update_profile})

# Api views
def api(request):
    return render(request,'project/api.html')

class ProjectList(APIView):
    def get(self,response,format=None):
        projects=Project.objects.all()
        serializer=ProjectSerailizer(projects,many=True)
        return Response(serializer.data)
    
    @login_required
    def post(self,request,format=None):
        permission_classes=(IsAdminOrReadOnly,)
        serializer=ProjectSerailizer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    
        permission_classes=(IsAdminOrReadOnly,)

class UserList(APIView):
    def get(self,response,format=None):
        users=User.objects.all()
        serializer=UserSerializer(users,many=True)
        return Response(serializer.data)
 
 # Gets project by id 
class ProjectDescription(APIView):
    permission_classes=(IsAdminOrReadOnly,)  
    def get_project(self,pk):
        return get_object_or_404(Project,pk=pk)
    # gets project by id
    def get(self, request, pk ,format=None):
        project= self.get_project(pk)
        serializer=ProjectSerailizer(project)
        return Response(serializer.data)
    # updates a specific project
    def put(self, request,pk, format=None):
        project=self.get_project(pk)
        serializer=ProjectSerailizer(project,request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    # Deletes a pjoect 
    def delete(self,request,pk,format=None):
        project=self.get_project(pk)
        project.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
        
# Gets User by id     
class UserDescription(APIView):
    permission_classes=(IsAdminOrReadOnly,)  
    def get_user(self,pk):
        return get_object_or_404(User,pk=pk)
    # Gets user by id
    def get(self, request, pk ,format=None):
        user= self.get_user(pk)
        serializer=UserSerializer(user)
        return Response(serializer.data)
    # Updates a specific user
    def put(self, request,pk, format=None):
        user=self.get_user(pk)
        serializer=UserSerializer(user,request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    # Deletes a user   
    def delete(self,request,pk,format=None):
        user=self.get_user(pk)
        user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

projects/templates/project/api.html
{%extends "project/base.html"%}
{% load bootstrap3%}
{% block content %}
<div class="container">
  <div class="row">
      <div class="co-lg-2 col-md-2"></div>
      <div class="co-lg-8 col-md-8 mb-3">
          <legend class="text-center">How to use Award Gallery Api</legend>
          <div>
              <div>For better user experience and for developers who would like to use our Awards App data, we
                  developed an <span style="font-weight: bolder;">API</span> that will help you out. To use our api we recommend
                  to you to use it on <a href="https://www.postman.com/downloads/">Postman</a> which is much easier to send the HTTP request 
                  i.e GET,POST,PUT,DELETE...
              </div><br>
              <div>
                Before you start using our api endpoints, you need an <span style="font-weight: bolder;">Autheniticaton Token</span>. On Postman 
                choose the POST http request method on the url place this url <span style="color: blueviolet;">https://moringaawards.herokuapp.com/api-auth-token/</span> on the body
                on the postman. Pass your USERNAME and PASSWORD as the key and value. On the request results at the bottom of postman
                if successful, you will get your token.               
              </div><br>
              <div>
                After receiving the token you can now access <span style="font-weight: bolder; color: blueviolet;">user</span> and <span style="font-weight: bolder; color: blueviolet;">project</span> data using the following 
                links <span style="color: blueviolet;">https://moringaawards.herokuapp.com/api/users/</span> and <span style="color: blueviolet;">https://moringaawards.herokuapp.com/api/project/</span> respectively.
              </div><br>
              <div style="font-style: italic;">
                  Thank You. <br>
                  Regards Nyururu Kelvin (developer)
              </div>
          </div>
      </div>
      <div class="co-lg-2 col-md-2"></div>
  </div>
</div>

{% endblock %}

projects/templates/project/base.html
{% load bootstrap3 %}
{% load static%}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="referrer" content="origin-when-cross-origin" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  {% if title %}
  <title>Projects Gallery - {{title}}</title>
  {% else %}
    <title> Projects Gallery </title>
  {% endif %}

  {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
  {% endblock %}

</head>
<body>
    {% include 'navbar.html' %}
    <div class="text-center">
      {% if messages %}
        {% for message in messages%}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
        {% endfor%}
      {% endif %}
  </div>

    {% block content %}

    {%endblock%}

    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        {% bootstrap_javascript %}
    {% endblock %}
</body>
</html>

projects/templates/project/new_project.html
{% extends 'project/base.html'%}
{% load bootstrap3 %} 
{% load static %}
{% block content%}
<div class="container mt-3 mb-5">
    <div class="row">
        <div class="col-lg-2 col-md-2 col-xs-0"></div>
        <div class="col-lg-8 col-md-8">
            <legend class="text-center border ">Create Your Project For Display</legend>
            <form  action="{% url 'new_project'%}" method="post" enctype="multipart/form-data">
                {%csrf_token%}

                {% bootstrap_form form%}
                <input type="submit" class="btn btn-success btn-block" value="Submit Project">
            </form>
        </div>
        <div class="col-lg-2 col-md-2 col-xs-0"></div>
    </div>
</div>
{% endblock%}

projects/templates/project/posted_by.html
{% extends 'project/base.html'%}
{% load bootstrap3 %} 
{% load static %}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{%static 'css/index.css'%}"  >
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-lg-2"></div>
        <div class="col-md-8 col-lg-8 col-sm-10">
            <div class="card  mt-3">
                <!-- new conatiner -->
                <div class="container-fluid" >
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-xs-12 ml-2 mt-2 ">
                            <img src="{{user.profile.image.url}}" class="img-circle rounded-circle image-fluid" alt="..." style="width: 220px; height: 220px;">
                        </div>
                    
                        <div class="col-lg-6 col-md-6 col-xs-12 mb-2" style="font-size: 0.8rem;">
                            <h2 class="card-title">{{user.username}}</h2>
                            <p class="card-text">Email Adress: {{user.email}}</p>
                            {% if user.profile.company%}
                            <p class="card-text">Location: {{user.profile.company}}</p>
                            {%endif%} 
                            {% if user.profile.location%}
                            <p class="card-text">Location: {{user.profile.location}}</p>
                            {%endif%} 
                            {% if user.profile.contact%}
                            <p class="card-text">Contact Me: {{user.profile.contact}}</p>
                            {%endif%} 
                            {% if user.profile.bio%}
                            <p class="card-text">About Me: {{user.profile.bio}}</p>
                            {%endif%} 
                            {% if request.user.id is user.id%}
                            <a href="#" class="btn btn-success btn-sm"><small>Update Settings</small></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-lg-2"></div>
    </div>

    <div class="row mt-3">
        <div class="col-lg-12 col-md-12" >
            <div class="row">
                {%for image in user.project_set.all%}
                <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
                    <div class="card" style="margin-left: 0px;">
                        <a href="#"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:50vh; width: 100%;" ></a>
                        <div class="card-body">
                            <div class="card-body">
                                <h5 class="card-title">{{image.title}}</h5>
                                <p>By <a href="{% url 'posted_by'%}">{{image.user.username}}</a><span class="float-right">From {{image.location}}</span></p>
                                <div class="text-center"><a class="btn button text-center btn-block"  href="{{image.link}}">Visit Site</a></div>
                            </div>
                        </div>  
                    </div>               
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock%}

projects/templates/project/profile.html
{% extends 'project/base.html'%}
{% load bootstrap3 %} 
{% load static %}
{% block title%}
{{user.username}}
{% endblock%}

{% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{%static 'css/index.css'%}"  >
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-lg-2"></div>
        <div class="col-md-8 col-lg-8 col-sm-10">
            <div class="card  mt-3">
                <!-- new conatiner -->
                <div class="container-fluid" >
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-xs-12 ml-2 mt-2 " style="margin-top: 2%;">
                            <img src="{{user.profile.image.url}}" class="img-circle rounded-circle image-fluid" alt="..." style="width: 220px; height: 220px;">
                        </div>
                    
                        <div class="col-lg-6 col-md-6 col-xs-12 mb-2">
                            <h2 class="card-title">{{user.username}}</h2>
                            <p class="card-text">Email Adress: {{user.email}}</p>
                            {% if user.profile.company%}
                            <p class="card-text">Institution: {{user.profile.company}}</p>
                            {%endif%} 
                            {% if user.profile.location%}
                            <p class="card-text">Location: {{user.profile.location}}</p>
                            {%endif%} 
                            {% if user.profile.contact%}
                            <p class="card-text">Contact: {{user.profile.contact}}</p>
                            {%endif%} 
                            {% if user.profile.bio%}
                            <p class="card-text">Bio: {{user.profile.bio}}</p>
                            {%endif%} 
                
                            <a href="{% url  'update_profile' %}" class="btn btn-success btn-sm">Update Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-lg-2"></div>
    </div>
    <legend class="text-center">PROJECTS POSTED</legend>
    <div class="row mt-3">
        <div class="col-lg-12 col-md-12" >
            <div class="row">
                {%for image in user.project_set.all%}
                <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
                    <div class="card" style="margin-left: 0px;">
                        <a href="#"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:50vh; width: 100%;" ></a>
                        <div class="card-body">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">{{image.title}}</h5>
                                <div class="text-center"><a class="btn button text-center btn-block"  href="{{image.link}}">View site details</a></div>
                            </div>
                        </div>  
                    </div>               
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock%}

projects/templates/project/project.html
{% extends 'project/base.html'%}
{% load bootstrap3 %}
{% load static %}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{%static 'css/register.css'%}"  >
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 5px;">
    <div class="row mt-3 mb-3">
        <div class="col-mg-5 col-col-md-5 col-xs-6" >
            <img src="{{project.image.url}}" alt="" style="width: 100%; height: 70vh;" class="image-responsive">
        </div>
        <div class="col-mg-7 col-col-md-7 col-xs-6 ml-3 mt-3">
            <div class="form-inline"><h5>By: <a href="{% url 'profile' %}">{{project.user.username}}</a></h5><span class="small ml-3">{{project.posted |  date:"M d,Y,f A"}}</span></div>
            <h5 style="font-weight: bolder;">Description:</h5>
            <p>{{project.description}}</p>
            <div>
                <p>
                    <a class="btn btn-primary btn-block btn-sm" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                      Vote Now
                    </a>
                  </p>
                  <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        <form action="{% url 'vote' project.id %}" method="post">
                        {% csrf_token%}

                        {% bootstrap_form form%}
                        <input type="submit" value="Vote" class="btn btn-success btn-sm text-center">
                        </form>
                    </div>
                  </div>
                  
            </div>
        </div>
    </div>
    <div class="row mb-4"> <br>
        <legend style="text-align: center; margin-bottom: 0%;">RATINGS</legend>
    <div class="col-lg-12 col-md-12">
        {%if votes_list%}
            {% for vote in votes_list%}
                <div>
                    <table class="table">
                        <thead class="thead" style="background-color: #60b4df;">
                        <tr>
                            <th scope="col">User</th>
                            <th scope="col">Usability</th>
                            <th scope="col">Content</th>
                            <th scope="col">Design</th>
                            <th scope="col">Mean</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td scope="col">{{vote.user.username}}</td>
                            <td scope="col">{{vote.usability}}</td>
                            <td scope="col">{{vote.content}}</td>
                            <td scope="col">{{vote.design}}</td>
                            <td scope="col">{{mean}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            {% endfor %}
        {%else%}
        <div>
            <table class="table">
                <thead class="thead" style="background-color: #60b4df;">
                  <tr>
                    <th scope="col">User</th>
                    <th scope="col">Usability</th>
                    <th scope="col">Content</th>
                    <th scope="col">Design</th>
                    <th scope="col">Mean</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                  </tr>
                </tbody>
              </table>
        </div>

        {% endif %}
    </div>
    </div>
</div>
{% endblock %}

projects/templates/project/search.html
{%extends 'project/base.html'%}
{% load bootstrap3 %}
{% load static %}

{% block styles %}
  {% bootstrap_css %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
{{block.super}}
<div class="container">

  <div class="row">
    {% if projects %}
    <legend class="header" style="color: rgb(20, 20, 20); text-align: center;">Searches for {{message}} </legend>
    {% else %}
    <legend class="header" style="color: rgb(12, 12, 12); text-align: center;">FOUND 0 PROJECTS</legend>
    {% endif %}

  </div>
  <div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
        <div class="card" style="margin-left: 0px;">
            <a href="#"><img src="{{project.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:50vh; width: 100%;" ></a>
            <div class="card-body">
                <div class="card-body">
                    <h5 class="card-title">{{image.title}}</h5>
                    <p>By <a href="{% url 'profile' %}">{{project.user.username}}</a><span class="float-right"> From {{project.location}}</span></p>
                    <div class="text-center"><a class="btn button text-center btn-block"  href="{{project.link}}">View site details</a></div>
                </div>
            </div>  
        </div>               
    </div>
    {% endfor %}

  </div>

</div>
{% endblock %}

projects/templates/project/update_profile.html
{%extends "project/base.html"%}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Empty div -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="text-center">Update Profile</h3>
        </div>
        <div class="panel-body">

          <form  action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form update_user%}
            {% bootstrap_form update_profile%}
            <div class="form-group">
              <input type="submit" class="btn btn-primary btn-sm float-right" value="Update">
            </div>

            <input type="hidden" name="next" value="{{next}}">

          </form>

        </div>

      </div>

    </div>
    <!-- empty div -->
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock %}